import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Copy, CreditCard, FileText, KeyRound, LayoutDashboard, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useState, type FormEvent } from 'react';
import { api, jsonInit } from '../../shared/api';
import { Badge, Button, Card, Dialog, Empty, Loading, SelectField } from '../../shared/ui';

type Key={id:string;name:string;key_prefix:string;created_at:string;last_used_at?:string};
type Usage={quota:number|null;used:number;remaining:number|null};
type Order={id:string;bucket:'cv'|'interview';units:number;unit_price_vnd:number;amount_vnd:number;status:string;created_at:string;approved_at?:string};
type ApiApplication={id:string;name:string;email:string;phone?:string;job_id:string;level?:string;status:string;applied_at:string;cv_score?:number|null;score_breakdown?:Record<string,unknown>;ai_summary?:string;cv_extracted_info?:Record<string,unknown>;interview_link?:string;interview_link_sent_at?:string};
type Portal={company:{name:string;slug:string};keys:Key[];usage:{cv:Usage;interview:Usage};orders:Order[]};
type LoginResponse={token:string;account:{email:string};portal:Portal};
type Payment={order_id:string;payment_code:string;amount_vnd:number;qr_url:string;message:string};
// Keep the opaque enterprise session across a normal page navigation.  Safari
// can discard sessionStorage during a full SPA reload in some privacy modes.
const enterpriseToken=()=>sessionStorage.getItem('pai_enterprise_token')||localStorage.getItem('pai_enterprise_token')||'';
// Portal requests authenticate with the HttpOnly session cookie set at login.
// Do not attach a potentially stale browser token; this keeps key creation,
// billing and application listing reliable behind reverse proxies.
const auth=()=>({});
const money=(value:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(value);
const date=(value?:string)=>value?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(`${value.replace(' ','T')}Z`)):'—';
function portalResponse(value: unknown): Portal { if (!value || typeof value !== 'object' || !(value as {company?:unknown}).company) throw new Error('Không nhận được dữ liệu portal hợp lệ.'); return value as Portal; }

export function EnterprisePortalPage(){
  const [keyName,setKeyName]=useState('Khóa production'); const [rawKey,setRawKey]=useState(''); const [error,setError]=useState(''); const [account,setAccount]=useState(''); const [password,setPassword]=useState(''); const [tab,setTab]=useState<'overview'|'keys'|'applications'|'billing'>('overview'); const [bucket,setBucket]=useState<'cv'|'interview'>('cv'); const [units,setUnits]=useState('100'); const [revokeKey,setRevokeKey]=useState<Key>(); const [selectedApplication,setSelectedApplication]=useState<string>(); const [notice,setNotice]=useState(''); const [payment,setPayment]=useState<Payment>(); const qc=useQueryClient(); const navigate=useNavigate();
  const portal=useQuery({queryKey:['enterprise-portal'],retry:false,queryFn:async()=>portalResponse(await api<unknown>('/api/enterprise/portal',auth()))});
  const applications=useQuery({queryKey:['enterprise-api-applications'],enabled:portal.isSuccess,queryFn:()=>api<{total:number;applications:ApiApplication[]}>('/api/enterprise/portal/applications',auth())});
  const applicationDetail=useQuery({queryKey:['enterprise-api-application',selectedApplication],enabled:!!selectedApplication,queryFn:()=>api<ApiApplication>(`/api/enterprise/portal/applications/${encodeURIComponent(selectedApplication||'')}`,auth())});
  const refresh=()=>qc.invalidateQueries({queryKey:['enterprise-portal']});
  const createKey=useMutation({mutationFn:()=>api<{api_key:string}>('/api/enterprise/portal/keys',{...jsonInit('POST',{name:keyName}),...auth()}),onSuccess:data=>{setRawKey(data.api_key);setTab('keys');refresh();},onError:e=>setError(e.message)});
  const revoke=useMutation({mutationFn:(id:string)=>api(`/api/enterprise/portal/keys/${id}`,{method:'DELETE',...auth()}),onSuccess:refresh,onError:e=>setError(e.message)});
  const paymentStatus=useQuery({queryKey:['enterprise-topup',payment?.order_id],enabled:!!payment?.order_id,refetchInterval:payment?3000:false,queryFn:()=>api<{status:string}>(`/api/enterprise/portal/topups/${encodeURIComponent(payment?.order_id||'')}`,auth())});
  const topup=useMutation({mutationFn:()=>api<Payment>('/api/enterprise/portal/topups',{...jsonInit('POST',{bucket,units:Number(units)}),...auth()}),onSuccess:data=>{setError('');setPayment(data);setTab('billing');refresh();},onError:e=>setError(e.message)});
  const login=useMutation({mutationFn:()=>api<LoginResponse>('/api/enterprise/login',jsonInit('POST',{account,password})),onSuccess:data=>{sessionStorage.removeItem('pai_enterprise_token');localStorage.removeItem('pai_enterprise_token');qc.removeQueries({queryKey:['enterprise-api-applications']});qc.setQueryData(['enterprise-portal'],data.portal);navigate('/enterprise/dashboard',{replace:true});},onError:e=>setError(e.message)});
  if(portal.isLoading)return <main className="page-container"><p className="muted">Đang tải khu vực doanh nghiệp…</p></main>;
  if(portal.isError)return <main className="page-container"><Card className="mx-auto max-w-xl p-7"><Link to="/enterprise" className="text-sm font-bold text-brand-700">← Tài liệu API</Link><p className="eyebrow mt-6">Khu vực doanh nghiệp</p><h1 className="section-title mt-2">Đăng nhập doanh nghiệp</h1><p className="muted mt-3">Tài khoản doanh nghiệp tách biệt với tài khoản ứng viên.</p>{enterpriseToken()&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">Phiên đăng nhập không còn hợp lệ. Vui lòng đăng nhập lại.</p>}<form className="mt-6 space-y-4" onSubmit={(event:FormEvent)=>{event.preventDefault();setError('');login.mutate();}}><label><span className="label">Email doanh nghiệp</span><input className="field" value={account} onChange={e=>setAccount(e.target.value)} required autoComplete="username"/></label><label><span className="label">Mật khẩu</span><input className="field" type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><Link to={`/reset-password?type=enterprise${account?'&email='+encodeURIComponent(account):''}`} className="-mt-1 inline-block text-sm font-bold text-brand-700 hover:underline">Quên mật khẩu?</Link>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<Button className="w-full" disabled={login.isPending}>{login.isPending?'Đang đăng nhập...':'Đăng nhập doanh nghiệp'}</Button></form></Card></main>;
  const data=portal.data!;
  // A stale gateway can respond with a valid JSON payload that is not the
  // applications contract (for example an error envelope). Never let that
  // response take down the whole enterprise dashboard.
  const apiApplications=Array.isArray(applications.data?.applications) ? applications.data.applications : [];
  const purchase=()=>{setError('');topup.mutate();};
  return <main className="min-h-screen bg-slate-50"><div className="border-b border-slate-200 bg-navy-950 text-white"><div className="page-container py-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link to="/enterprise" className="text-sm font-bold text-blue-200 hover:text-white">← Tài liệu API</Link><p className="mt-5 text-xs font-extrabold uppercase tracking-[.2em] text-blue-300">Bảng điều khiển doanh nghiệp</p><h1 className="mt-2 text-3xl font-extrabold">{data.company.name}</h1><p className="mt-2 text-sm text-slate-300">Quản lý lượt sử dụng, thanh toán và khóa tích hợp trong một nơi.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm"><p className="text-slate-300">Tài khoản</p><p className="mt-1 font-extrabold">Đang hoạt động <ShieldCheck className="ml-1 inline h-4 w-4 text-emerald-300"/></p></div></div></div></div><div className="page-container py-7"><nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">{([{id:'overview',label:'Tổng quan',icon:LayoutDashboard},{id:'keys',label:'API key',icon:KeyRound},{id:'applications',label:'Hồ sơ từ API',icon:FileText},{id:'billing',label:'Lượt & thanh toán',icon:CreditCard}] as const).map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-extrabold ${tab===item.id?'bg-navy-950 text-white':'text-slate-600 hover:bg-slate-100'}`}><Icon className="h-4 w-4"/>{item.label}</button>})}</nav>
    {tab==='overview'&&<><div className="mt-6 grid gap-4 md:grid-cols-2"><UsageCard title="Lượt chấm CV" text="Mỗi lần gọi score-cv" value={data.usage.cv}/><UsageCard title="Lượt phỏng vấn" text="Mỗi lần tạo lịch phỏng vấn" value={data.usage.interview}/></div><Card className="mt-6 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-extrabold text-slate-950">Bắt đầu tích hợp</h2><p className="muted mt-1">Tạo key và dùng trong header Authorization.</p></div><Button onClick={()=>setTab('keys')}>Quản lý key</Button></div><pre className="mt-5 overflow-x-auto rounded-2xl bg-slate-950 p-4 text-xs leading-6 text-emerald-300"><code>{`Authorization: Bearer pai_${data.company.slug}_...`}</code></pre></Card></>}
    {tab==='keys'&&<><Card className="mt-6 p-6"><div className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1"><span className="label">Tên API key</span><input className="field" value={keyName} onChange={e=>setKeyName(e.target.value)} maxLength={80}/></label><Button disabled={createKey.isPending} onClick={()=>createKey.mutate()}><Plus className="h-4 w-4"/>Tạo API key</Button></div>{error&&<p className="mt-3 text-sm font-bold text-red-700">{error}</p>}</Card>{rawKey&&<Card className="mt-5 border-amber-200 bg-amber-50 p-6"><p className="font-extrabold text-amber-900">Sao chép key ngay — chỉ hiển thị một lần</p><code className="mt-4 block overflow-x-auto rounded-xl bg-slate-950 p-4 text-sm text-emerald-300">{rawKey}</code><Button variant="secondary" className="mt-4" onClick={()=>navigator.clipboard.writeText(rawKey)}><Copy className="h-4 w-4"/>Sao chép</Button></Card>}<Card className="mt-5 overflow-hidden"><div className="border-b border-slate-200 p-6"><h2 className="font-extrabold">API key đang hoạt động</h2></div>{data.keys.length?<div className="divide-y divide-slate-100">{data.keys.map(key=><div key={key.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-bold">{key.name}</p><code className="text-xs text-slate-500">{key.key_prefix}…</code><p className="mt-1 text-xs text-slate-400">Dùng gần nhất: {date(key.last_used_at)}</p></div><Button variant="danger" onClick={()=>setRevokeKey(key)}><Trash2 className="h-4 w-4"/>Thu hồi</Button></div>)}</div>:<Empty title="Chưa có API key"/>}</Card></>}
    {tab==='applications'&&<Card className="mt-6 overflow-hidden"><div className="border-b border-slate-200 p-6"><p className="eyebrow">Dữ liệu thuộc doanh nghiệp</p><h2 className="section-title mt-2">Hồ sơ gửi qua API</h2><p className="muted mt-1">Chỉ hiển thị hồ sơ được tạo bằng API key của {data.company.name}.</p></div>{applications.isLoading?<Loading/>:applications.error?<Empty title="Không thể tải hồ sơ API" description={(applications.error as Error).message}/>:apiApplications.length?<div className="divide-y divide-slate-100">{apiApplications.map(app=><div className="flex flex-wrap items-center justify-between gap-4 p-5 transition hover:bg-blue-50/60" key={app.id}><button type="button" onClick={()=>setSelectedApplication(app.id)} className="min-w-0 flex-1 text-left"><p className="font-extrabold text-slate-950">{app.name}</p><p className="mt-1 text-sm text-slate-500">{app.email} · {app.phone||'Không có số điện thoại'}</p><p className="mt-1 text-xs text-slate-400">Nhận lúc {date(app.applied_at)} · Cấp bậc {app.level||'—'}</p></button><div className="flex items-center gap-3"><div className="text-right"><Badge tone={app.interview_link?'success':'warning'}>{app.interview_link?'Đã cấp link phỏng vấn':'Đã chấm CV'}</Badge><p className="mt-2 text-xs text-slate-500">{app.interview_link_sent_at?`Gửi link: ${date(app.interview_link_sent_at)}`:'Chưa gửi link'}</p></div><Button variant="secondary" onClick={()=>setSelectedApplication(app.id)}>Xem hồ sơ</Button></div></div>)}</div>:<Empty title="Chưa có hồ sơ từ API" description="Hồ sơ sẽ hiện tại đây sau khi gọi score-cv hoặc schedule-with-cv."/>}</Card>}
    {tab==='billing'&&<div className="mt-6 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><Card className="p-6"><p className="eyebrow">Mua lượt</p><h2 className="section-title mt-2">Nạp quota sử dụng</h2><p className="muted mt-2">Sau khi tạo yêu cầu, quét mã QR thanh toán. Với VietinBank, giữ nguyên nội dung bắt đầu bằng SEVQR để SePay tự nhận giao dịch và cộng lượt.</p><div className="mt-6"><span className="label">Dịch vụ</span><SelectField value={bucket} onChange={value=>setBucket(value as 'cv'|'interview')} options={[{value:'cv',label:'Chấm CV · 1.000đ / lượt'},{value:'interview',label:'Tạo lịch phỏng vấn · 3.000đ / lượt'}]}/><p className="mt-2 text-xs text-slate-500">{bucket==='cv'?'Dùng cho mỗi lần phân tích và chấm hồ sơ qua API.':'Dùng cho mỗi lần tạo lịch phỏng vấn kèm CV qua API.'}</p></div><label className="mt-4 block"><span className="label">Số lượt</span><input className="field" type="number" min="10" max="100000" value={units} onChange={e=>setUnits(e.target.value)}/></label><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Tạm tính</p><p className="mt-1 text-2xl font-extrabold">{money((Number(units)||0)*(bucket==='cv'?1000:3000))}</p></div>{error&&<p className="mt-3 text-sm font-bold text-red-700">{error}</p>}<Button className="mt-5 w-full" disabled={topup.isPending} onClick={purchase}>{topup.isPending?'Đang tạo yêu cầu...':'Tạo yêu cầu thanh toán'}</Button></Card><Card className="overflow-hidden"><div className="border-b border-slate-200 p-6"><h2 className="font-extrabold">Lịch sử mua lượt</h2></div>{data.orders.length?<div className="divide-y divide-slate-100">{data.orders.map(order=><div className="flex flex-wrap items-center justify-between gap-3 p-5" key={order.id}><div><p className="font-bold">{order.bucket==='cv'?'Chấm CV':'Lịch phỏng vấn'} · {order.units.toLocaleString('vi-VN')} lượt</p><p className="mt-1 text-xs text-slate-500">{order.id} · {date(order.created_at)}</p></div><div className="text-right"><p className="font-extrabold">{money(order.amount_vnd)}</p><Badge tone={order.status==='approved'?'success':'warning'}>{order.status==='approved'?'Đã cộng lượt':'Chờ xác nhận thanh toán'}</Badge></div></div>)}</div>:<Empty title="Chưa có yêu cầu mua lượt" description="Chọn gói ở bên trái để bắt đầu."/>}</Card></div>}
  <Dialog open={!!revokeKey} onClose={()=>setRevokeKey(undefined)} title="Thu hồi API key?" description={`Key “${revokeKey?.name||''}” sẽ ngừng hoạt động ngay. Các hệ thống đang dùng key này sẽ không gọi API được.`} danger confirmLabel={revoke.isPending?'Đang thu hồi...':'Thu hồi key'} onConfirm={()=>revokeKey&&revoke.mutate(revokeKey.id,{onSuccess:()=>setRevokeKey(undefined)})}/><Dialog open={!!payment} onClose={()=>setPayment(undefined)} title={paymentStatus.data?.status==='approved'?'Thanh toán thành công':'Quét QR để thanh toán'} confirmLabel={paymentStatus.data?.status==='approved'?'Đã hiểu':'Tôi sẽ thanh toán'} onConfirm={()=>setPayment(undefined)}>{payment&&<div className="mt-4 text-center"><p className="text-sm font-semibold text-slate-600">{paymentStatus.data?.status==='approved'?'Lượt đã được cộng vào tài khoản.':payment.message}</p><img className="mx-auto mt-4 w-64 rounded-2xl border border-slate-200 bg-white p-2" src={payment.qr_url} alt="Mã QR thanh toán"/><p className="mt-3 text-2xl font-extrabold text-slate-950">{money(payment.amount_vnd)}</p><p className="mt-2 text-xs font-bold text-slate-500">Nội dung chuyển khoản: <code className="select-all text-brand-700">{payment.payment_code}</code></p><p className="mt-2 text-xs text-slate-400">Hệ thống tự kiểm tra thanh toán. Vui lòng giữ nguyên nội dung chuyển khoản.</p></div>}</Dialog><Dialog open={!!notice} onClose={()=>setNotice('')} title="Đã tạo yêu cầu thanh toán" description={notice} confirmLabel="Đã hiểu" onConfirm={()=>setNotice('')}/><Dialog open={!!selectedApplication} onClose={()=>setSelectedApplication(undefined)} title={applicationDetail.data?.name||'Chi tiết hồ sơ API'}>{applicationDetail.isLoading?<Loading/>:applicationDetail.error?<Empty title="Không thể tải hồ sơ" description={(applicationDetail.error as Error).message}/>:applicationDetail.data?<div className="mt-5 space-y-4"><div className="rounded-2xl bg-slate-50 p-4"><p className="font-extrabold">{applicationDetail.data.email}</p><p className="mt-1 text-sm text-slate-500">{applicationDetail.data.phone||'Không có số điện thoại'} · {applicationDetail.data.level||'—'}</p><p className="mt-3 text-sm leading-6 text-slate-700">{applicationDetail.data.ai_summary||'Chưa có tóm tắt AI.'}</p></div><div><p className="label">Thông tin trích xuất từ CV</p><pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-200">{JSON.stringify(applicationDetail.data.cv_extracted_info||{},null,2)}</pre></div>{applicationDetail.data.interview_link&&<div><p className="label">Link phỏng vấn đã cấp</p><a className="mt-2 block break-all text-sm font-bold text-brand-700" href={applicationDetail.data.interview_link} target="_blank" rel="noreferrer">{applicationDetail.data.interview_link}</a></div>}</div>:null}</Dialog></div></main>;
}
function UsageCard({title,text,value}:{title:string;text:string;value:Usage}){const unlimited=value.quota===null;const percent=unlimited?0:Math.min(100,value.used/(value.quota||1)*100);return <Card className="p-6"><p className="text-sm font-bold text-slate-600">{title}</p><p className="mt-1 text-xs text-slate-400">{text}</p><p className="mt-5 text-3xl font-extrabold text-slate-950">{value.remaining??'∞'} <span className="text-sm text-slate-400">lượt còn lại</span></p><p className="mt-1 text-sm text-slate-500">Đã dùng {value.used} / {unlimited?'không giới hạn':value.quota}</p>{!unlimited&&<div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600" style={{width:`${percent}%`}}/></div>}</Card>}
