import { useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api, jsonInit } from '../../shared/api';
import { Button, Card } from '../../shared/ui';

export function ResetPasswordPage(){
  const [params]=useSearchParams(); const type=params.get('type')==='enterprise'?'enterprise':'user'; const token=params.get('token')||''; const initialEmail=params.get('email')||'';
  const [email,setEmail]=useState(initialEmail); const [code,setCode]=useState(token); const [requested,setRequested]=useState(Boolean(token)); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const enterprise=type==='enterprise'; const back=enterprise?'/enterprise/dashboard':'/apply';
  const request=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const result=await api<{message:string}>('/auth/password-reset/request',jsonInit('POST',{email,account_type:type}));setMessage(result.message);setRequested(true)}catch(e){setError(e instanceof Error?e.message:'Không thể gửi yêu cầu')}finally{setBusy(false)}};
  const reset=async(event:FormEvent)=>{event.preventDefault();setError('');if(password!==confirm){setError('Mật khẩu xác nhận chưa khớp');return}setBusy(true);try{const result=await api<{message:string}>('/auth/password-reset/confirm',jsonInit('POST',{token:code,account_type:type,password}));setMessage(result.message)}catch(e){setError(e instanceof Error?e.message:'Không thể đặt lại mật khẩu')}finally{setBusy(false)}};
  return <main className="page-container py-10 sm:py-16"><Card className="mx-auto max-w-lg p-6 sm:p-8"><Link className="text-sm font-bold text-brand-700" to={back}>← Quay lại đăng nhập</Link><p className="eyebrow mt-6">Bảo mật tài khoản</p><h1 className="section-title mt-2">{enterprise?'Quên mật khẩu doanh nghiệp':'Quên mật khẩu'}</h1><p className="muted mt-2">{requested?'Nhập mã 6 số đã gửi đến email tài khoản.':'Nhập email đã đăng ký để nhận mã xác nhận 6 số. Mã có hiệu lực 60 phút.'}</p>{message&&requested?<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-800">{message}</p>:null}{message&&message.startsWith('Đã đặt lại')?<div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}<Link className="mt-3 block font-extrabold underline" to={back}>Quay về đăng nhập</Link></div>:requested?<form className="mt-6 space-y-4" onSubmit={reset}><label><span className="label">Mã xác nhận</span><input className="field text-center text-xl font-extrabold tracking-[.45em]" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} autoComplete="one-time-code" required/></label><label><span className="label">Mật khẩu mới</span><input className="field" type="password" minLength={enterprise?10:6} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" required/></label><label><span className="label">Xác nhận mật khẩu mới</span><input className="field" type="password" minLength={enterprise?10:6} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<Button className="w-full" disabled={busy}>{busy?'Đang lưu...':'Xác nhận và đổi mật khẩu'}</Button><button type="button" className="w-full text-sm font-bold text-brand-700" onClick={()=>{setRequested(false);setMessage('');setCode('')}}>Dùng email khác</button></form>:<form className="mt-6 space-y-4" onSubmit={request}><label><span className="label">Email tài khoản</span><input className="field" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<Button className="w-full" disabled={busy}>{busy?'Đang gửi...':'Gửi mã xác nhận'}</Button></form>}</Card></main>;
}
