import { zodResolver } from '@hookform/resolvers/zod';
import { LoaderCircle, X } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { api, jsonInit } from '../../shared/api';
import { authStore } from '../../shared/storage';
import type { User } from '../../shared/types';
import { Button } from '../../shared/ui';

const loginSchema=z.object({account:z.string().min(3,'Nhập email hoặc số điện thoại'),password:z.string().min(6,'Mật khẩu tối thiểu 6 ký tự')});
const registerSchema=z.object({name:z.string().min(2,'Nhập họ tên'),email:z.string().email('Email không hợp lệ'),phone:z.string().optional(),password:z.string().min(6,'Mật khẩu tối thiểu 6 ký tự')});
type Login=z.infer<typeof loginSchema>; type Register=z.infer<typeof registerSchema>; type AuthResponse={token:string;user:User};
export function AuthDialog({open,onClose,onSuccess}:{open:boolean;onClose:()=>void;onSuccess:()=>void}) { const [mode,setMode]=useState<'login'|'register'>('login'); const [error,setError]=useState(''); const login=useForm<Login>({resolver:zodResolver(loginSchema)}); const register=useForm<Register>({resolver:zodResolver(registerSchema)}); if(!open)return null; const submitLogin=login.handleSubmit(async values=>{setError('');try{const data=await api<AuthResponse>('/auth/login',jsonInit('POST',values));authStore.save(data.user,data.token);onSuccess()}catch(e){setError(e instanceof Error?e.message:'Không thể đăng nhập')}}); const submitRegister=register.handleSubmit(async values=>{setError('');try{const data=await api<AuthResponse>('/auth/register',jsonInit('POST',values));authStore.save(data.user,data.token);onSuccess()}catch(e){setError(e instanceof Error?e.message:'Không thể tạo tài khoản')}}); const busy=login.formState.isSubmitting||register.formState.isSubmitting;
return <div className="fixed inset-0 z-[160] grid place-items-center p-4"><button className="absolute inset-0 bg-navy-950/60 backdrop-blur-[6px]" onClick={onClose}/><div className="modal-enter relative w-full max-w-md overflow-hidden rounded-[28px] border border-white/80 bg-white shadow-[0_30px_90px_rgba(7,20,38,.34)]"><div className="hero-mesh px-6 py-6 text-white"><button className="absolute right-4 top-4 rounded-xl border border-white/10 bg-white/10 p-2 text-white backdrop-blur hover:bg-white/20" onClick={onClose}><X className="h-5 w-5"/></button><div className="flex items-center gap-3"><div><h2 className="text-xl font-extrabold">{mode==='login'?'Đăng nhập':'Tạo tài khoản'}</h2><p className="text-xs text-slate-300">Theo dõi toàn bộ quá trình ứng tuyển</p></div></div></div><div className="p-6">{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}{mode==='login'?<form onSubmit={submitLogin} className="space-y-4"><label><span className="label">Email hoặc số điện thoại</span><input className="field" {...login.register('account')}/><small className="text-red-600">{login.formState.errors.account?.message}</small></label><label><span className="label">Mật khẩu</span><input type="password" className="field" {...login.register('password')}/><small className="text-red-600">{login.formState.errors.password?.message}</small></label><button type="button" className="-mt-1 text-sm font-bold text-brand-700 hover:underline" onClick={()=>{const acc=login.getValues('account')||'';window.location.assign('/reset-password?type=user'+(acc?'&email='+encodeURIComponent(acc):''))}}>Quên mật khẩu?</button><Button className="w-full" disabled={busy}>{busy&&<LoaderCircle className="h-4 w-4 animate-spin"/>}Đăng nhập</Button></form>:<form onSubmit={submitRegister} className="space-y-4"><label><span className="label">Họ và tên</span><input className="field" {...register.register('name')}/></label><label><span className="label">Email</span><input className="field" {...register.register('email')}/></label><label><span className="label">Số điện thoại</span><input className="field" {...register.register('phone')}/></label><label><span className="label">Mật khẩu</span><input type="password" className="field" {...register.register('password')}/></label><Button className="w-full" disabled={busy}>{busy&&<LoaderCircle className="h-4 w-4 animate-spin"/>}Tạo tài khoản</Button></form>}<button className="mt-5 w-full text-center text-sm font-bold text-brand-700" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Chưa có tài khoản? Đăng ký':'Đã có tài khoản? Đăng nhập'}</button></div></div></div> }
