import { AlertCircle, Check, CheckCircle2, ChevronDown, LoaderCircle, X } from 'lucide-react';
import { useState } from 'react';
import type { ButtonHTMLAttributes, PropsWithChildren, ReactNode } from 'react';
import { cn } from './utils';

export function Button({variant='primary',className,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'danger'|'ghost'}){return <button className={cn(variant==='primary'&&'btn-primary',variant==='secondary'&&'btn-secondary',variant==='danger'&&'btn-danger',variant==='ghost'&&'btn text-slate-600 hover:bg-slate-100',className)} {...props}/>}
export function Badge({children,tone='neutral'}:PropsWithChildren<{tone?:'success'|'danger'|'warning'|'info'|'neutral'}>){const styles={success:'bg-emerald-50 text-emerald-700 ring-emerald-200',danger:'bg-red-50 text-red-700 ring-red-200',warning:'bg-amber-50 text-amber-800 ring-amber-200',info:'bg-blue-50 text-blue-700 ring-blue-200',neutral:'bg-slate-100 text-slate-700 ring-slate-200'};return <span className={cn('inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold ring-1 ring-inset',styles[tone])}>{children}</span>}
export function Card({children,className}:PropsWithChildren<{className?:string}>){return <section className={cn('surface',className)}>{children}</section>}

export type SelectOption={value:string;label:string};
export function SelectField({value,onChange,options,placeholder='Chọn một mục',className}:{value:string;onChange:(value:string)=>void;options:SelectOption[];placeholder?:string;className?:string}){
  const [open,setOpen]=useState(false); const selected=options.find(item=>item.value===value);
  return <div className={cn('relative',open&&'z-[250]',className)} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setOpen(false)}}>
    <button type="button" className={cn('field flex items-center justify-between gap-3 text-left',open&&'border-blue-500 bg-white ring-4 ring-blue-100/80')} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}><span className={cn('truncate',!selected&&'text-slate-400')}>{selected?.label||placeholder}</span><ChevronDown className={cn('h-4 w-4 shrink-0 text-slate-400 transition',open&&'rotate-180 text-blue-600')}/></button>
    {open&&<div className="select-menu absolute left-0 right-0 z-[140] mt-2 max-h-72 overflow-y-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-[0_22px_55px_rgba(15,23,42,.18)]" role="listbox">{options.map(item=><button type="button" role="option" aria-selected={item.value===value} key={item.value||'__all'} onMouseDown={event=>event.preventDefault()} onClick={()=>{onChange(item.value);setOpen(false)}} className={cn('flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition',item.value===value?'bg-blue-50 text-blue-700':'text-slate-700 hover:bg-slate-50')}><span className="truncate">{item.label}</span>{item.value===value&&<Check className="h-4 w-4 shrink-0"/>}</button>)}</div>}
  </div>;
}

export function Loading({label='Đang tải dữ liệu...'}:{label?:string}){return <div className="flex min-h-40 items-center justify-center gap-2 text-sm text-slate-500"><LoaderCircle className="h-5 w-5 animate-spin text-brand-600"/>{label}</div>}
export function Empty({title='Chưa có dữ liệu',description}:{title?:string;description?:string}){return <div className="flex min-h-40 flex-col items-center justify-center px-6 text-center"><div className="mb-3 rounded-full bg-slate-100 p-3"><AlertCircle className="h-5 w-5 text-slate-500"/></div><p className="font-bold text-slate-800">{title}</p>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="flex min-h-40 flex-col items-center justify-center px-6 text-center"><AlertCircle className="mb-3 h-7 w-7 text-red-500"/><p className="font-bold text-red-700">Không thể tải dữ liệu</p><p className="mt-1 text-sm text-slate-500">{message}</p>{retry&&<Button variant="secondary" className="mt-4" onClick={retry}>Thử lại</Button>}</div>}

export function Drawer({open,onClose,title,children,footer}:PropsWithChildren<{open:boolean;onClose:()=>void;title:string;footer?:ReactNode}>){if(!open)return null;return <div className="fixed inset-0 z-[100]" role="dialog" aria-modal="true"><button aria-label="Đóng nền" className="absolute inset-0 bg-navy-950/55 backdrop-blur-[5px]" onClick={onClose}/><aside className="drawer-enter absolute bottom-2 right-2 top-2 flex w-[calc(100%-1rem)] max-w-2xl flex-col overflow-hidden rounded-[26px] border border-white/80 bg-white shadow-[0_30px_90px_rgba(7,20,38,.32)] sm:bottom-3 sm:right-3 sm:top-3"><header className="relative flex items-center justify-between overflow-hidden border-b border-slate-100 px-5 py-5 sm:px-6"><div className="absolute inset-y-0 left-0 w-1.5 bg-gradient-to-b from-blue-500 to-indigo-600"/><div><p className="eyebrow">Chi tiết</p><h2 className="mt-1 text-lg font-extrabold text-slate-950">{title}</h2></div><button aria-label="Đóng" className="icon-btn border border-slate-200 bg-white shadow-sm" onClick={onClose}><X className="h-5 w-5"/></button></header><div className="flex-1 overflow-y-auto bg-slate-50/80 p-4 sm:p-6">{children}</div>{footer&&<footer className="border-t border-slate-100 bg-white/95 p-4 backdrop-blur sm:px-6">{footer}</footer>}</aside></div>}

export function Dialog({open,title,description,onClose,onConfirm,confirmLabel='Xác nhận',danger=false,children}:PropsWithChildren<{open:boolean;title:string;description?:string;onClose:()=>void;onConfirm?:()=>void;confirmLabel?:string;danger?:boolean}>){if(!open)return null;return <div className="fixed inset-0 z-[160] grid place-items-center p-4" role="dialog" aria-modal="true"><button aria-label="Đóng" className="absolute inset-0 bg-navy-950/60 backdrop-blur-[6px]" onClick={onClose}/><div className="modal-enter relative w-full max-w-[460px] overflow-hidden rounded-[26px] border border-white/80 bg-white p-6 shadow-[0_30px_90px_rgba(7,20,38,.34)] sm:p-7"><button aria-label="Đóng" className="icon-btn absolute right-4 top-4" onClick={onClose}><X className="h-5 w-5"/></button><h3 className="mt-5 text-xl font-extrabold tracking-tight text-slate-950">{title}</h3>{description&&<p className="mt-2 text-sm leading-6 text-slate-600">{description}</p>}{children}<div className="mt-7 grid grid-cols-2 gap-3"><Button variant="secondary" onClick={onClose}>Hủy</Button>{onConfirm&&<Button variant={danger?'danger':'primary'} onClick={onConfirm}>{confirmLabel}</Button>}</div></div></div>}
export function Success({title,description}:{title:string;description?:string}){return <div className="py-12 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-500"/><h2 className="mt-4 text-2xl font-extrabold">{title}</h2>{description&&<p className="mx-auto mt-2 max-w-lg text-slate-500">{description}</p>}</div>}
