import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Building2, ExternalLink } from 'lucide-react';
import { adminApi } from '../shared/api';
import type { Application } from '../shared/types';
import { Badge, Card, Drawer, Empty, ErrorState, Loading } from '../shared/ui';
import { formatDate } from '../shared/utils';

type ApiApplication={id:string;name:string;email:string;phone?:string;job_id:string;level?:string;status:string;applied_at:string;interview_link?:string;interview_link_sent_at?:string;company_id:string;company_name:string};
export function ApiApplicationsPage(){
  const [selected,setSelected]=useState<string>();
  const query=useQuery({queryKey:['admin-api-applications'],queryFn:()=>adminApi<{total:number;applications:ApiApplication[]}>('/admin/companies/api-applications')});
  return <div className="space-y-5"><Card className="p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Đa công ty</p><h2 className="section-title mt-2">Hồ sơ gọi qua API</h2><p className="muted mt-2">Theo dõi riêng các hồ sơ tạo bởi khách hàng API; mỗi hồ sơ luôn gắn công ty sở hữu.</p></div><div className="rounded-2xl bg-blue-50 px-4 py-3 text-right"><p className="text-xs font-bold text-blue-700">Tổng hồ sơ API</p><p className="text-2xl font-extrabold text-blue-950">{query.data?.total||0}</p></div></div></Card>
    <Card className="overflow-hidden">{query.isLoading?<Loading/>:query.error?<ErrorState message={query.error.message}/>:query.data?.applications.length?<div className="divide-y divide-slate-100">{query.data.applications.map(app=><article className="flex flex-wrap items-center justify-between gap-4 p-5 transition hover:bg-blue-50/60" key={app.id}><button type="button" onClick={()=>setSelected(app.id)} className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold text-slate-950">{app.name}</p><Badge tone="info"><Building2 className="mr-1 h-3 w-3"/>{app.company_name}</Badge></div><p className="mt-1 text-sm text-slate-600">{app.email} · {app.phone||'Không có số điện thoại'} · {app.level||'—'}</p><p className="mt-1 text-xs text-slate-400">{app.id} · Gọi API lúc {formatDate(app.applied_at)}</p></button><div className="flex items-center gap-3"><div className="text-right"><Badge tone={app.interview_link?'success':'warning'}>{app.interview_link?'Đã gửi link phỏng vấn':'Đã chấm CV'}</Badge><p className="mt-1 text-xs text-slate-500">{app.interview_link_sent_at?formatDate(app.interview_link_sent_at):'Chưa có lịch'}</p></div><button type="button" onClick={()=>setSelected(app.id)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-extrabold text-brand-700 hover:bg-white">Xem hồ sơ</button>{app.interview_link&&<a href={app.interview_link} target="_blank" rel="noreferrer" className="icon-btn border border-slate-200"><ExternalLink className="h-4 w-4"/></a>}</div></article>)}</div>:<Empty title="Chưa có hồ sơ gọi qua API" description="Hồ sơ sẽ xuất hiện khi doanh nghiệp gọi score-cv hoặc schedule-with-cv."/>}</Card><ApiApplicationDrawer id={selected} onClose={()=>setSelected(undefined)}/></div>;
}

function ApiApplicationDrawer({id,onClose}:{id?:string;onClose:()=>void}){
  const detail=useQuery({queryKey:['admin-api-application',id],enabled:!!id,queryFn:()=>adminApi<Application>(`/admin/applications/${id}`)});
  const app=detail.data;
  return <Drawer open={!!id} onClose={onClose} title={app?.name||'Chi tiết hồ sơ API'}>{detail.isLoading?<Loading/>:detail.error?<ErrorState message={detail.error.message}/>:app?<div className="space-y-4"><Card className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-slate-500">{app.email} · {app.phone||'Không có số điện thoại'}</p><p className="mt-2 text-xs font-extrabold uppercase tracking-wide text-brand-700">Hồ sơ gọi qua API</p><p className="mt-1 font-bold">Cấp bậc: {app.level||'—'}</p></div><Badge tone={app.interview_link?'success':'warning'}>{app.interview_link?'Đã gửi link':'Đã chấm CV'}</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">{app.ai_summary||'Chưa có tóm tắt AI.'}</p></Card>{app.cv_extracted_info&&<Card className="p-5"><h3 className="font-extrabold">Thông tin trích xuất từ CV</h3><pre className="mt-3 overflow-x-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-xs leading-6 text-slate-600">{JSON.stringify(app.cv_extracted_info,null,2)}</pre></Card>}{app.interview_link&&<Card className="p-5"><h3 className="font-extrabold">Link phỏng vấn</h3><a className="mt-3 block break-all text-sm font-bold text-brand-700" href={app.interview_link} target="_blank" rel="noreferrer">{app.interview_link}</a></Card>}</div>:null}</Drawer>;
}
