import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { adminApi, jsonInit } from '../shared/api';
import { Button, Card, Empty, ErrorState, Loading } from '../shared/ui';

type Usage={quota:number|null;used:number;remaining:number|null};
type QuotaOrder={id:string;company_name:string;bucket:'cv'|'interview';units:number;amount_vnd:number;status:string;created_at:string};
type Company={id:string;name:string;slug:string;is_active:boolean;key_count:number;tax_code?:string;company_size?:string;email?:string;phone?:string;created_at?:string;quota_cv?:number;quota_interview?:number;cv_used?:number;interview_used?:number};
type CreateResult={company?:Company;api_key:string;warning:string}; type ApprovalResult={success:true;onboarding_token?:string|null;warning:string};
const copy=async(value:string)=>navigator.clipboard.writeText(value);

export function IntegrationsPage(){
  const queryClient=useQueryClient(); const [created,setCreated]=useState<CreateResult>(); const [approval,setApproval]=useState<{company:Company;token?:string|null;warning:string}>(); const [notice,setNotice]=useState(''); const [editing,setEditing]=useState<Company>(); const [cvLimit,setCvLimit]=useState(''); const [interviewLimit,setInterviewLimit]=useState('');
  const companies=useQuery({queryKey:['companies'],queryFn:()=>adminApi<{companies:Company[]}>('/admin/companies')});
  const pending=useQuery({queryKey:['pending-companies'],queryFn:()=>adminApi<{companies:Company[]}>('/admin/companies/pending/list')});
  const orders=useQuery({queryKey:['quota-orders'],queryFn:()=>adminApi<{orders:QuotaOrder[]}>('/admin/companies/orders/pending')});
  const refresh=()=>{queryClient.invalidateQueries({queryKey:['companies']});queryClient.invalidateQueries({queryKey:['pending-companies']});queryClient.invalidateQueries({queryKey:['quota-orders']});};
  const approve=useMutation({mutationFn:(company:Company)=>adminApi<ApprovalResult>(`/admin/companies/${company.id}/approve`,jsonInit('POST',{})),onSuccess:(data,company)=>{setApproval({company,token:data.onboarding_token,warning:data.warning});refresh();}});
  const saveQuota=useMutation({mutationFn:(company:Company)=>adminApi<{quota:{cv:Usage;interview:Usage}}>(`/admin/companies/${company.id}/quota`,jsonInit('PATCH',{cv_limit:Number(cvLimit),interview_limit:Number(interviewLimit)})),onSuccess:()=>{setEditing(undefined);refresh();}});
  const createKey=useMutation({mutationFn:(company:Company)=>adminApi<{api_key:string;warning:string}>(`/admin/companies/${company.id}/keys`,jsonInit('POST',{name:'Khóa production'})),onSuccess:(data,company)=>{setCreated({company,api_key:data.api_key,warning:data.warning});refresh();}});
  const approveOrder=useMutation({mutationFn:(order:QuotaOrder)=>adminApi(`/admin/companies/orders/${order.id}/approve`,jsonInit('POST',{})),onSuccess:refresh});
  const rejectOrder=useMutation({mutationFn:(order:QuotaOrder)=>adminApi(`/admin/companies/orders/${order.id}/reject`,jsonInit('POST',{})),onSuccess:refresh});
  const startQuota=(company:Company)=>{setEditing(company);setCvLimit(String(company.quota_cv||0));setInterviewLimit(String(company.quota_interview||0));}; const origin=window.location.origin; const key=created?.api_key||'PAI_API_KEY';
  return <div className="space-y-5"><Card className="p-6"><p className="eyebrow">Đa công ty</p><h2 className="section-title mt-2">Yêu cầu đăng ký doanh nghiệp</h2><p className="muted mt-2">Duyệt tài khoản trước, sau đó cấu hình hạn mức CV và phỏng vấn riêng cho tài khoản đó.</p>{pending.isLoading?<Loading/>:pending.error?<ErrorState message={pending.error.message}/>:pending.data?.companies.length?<div className="mt-5 divide-y divide-slate-100">{pending.data.companies.map(company=><div key={company.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-extrabold text-slate-950">{company.name}</p><p className="mt-1 text-sm text-slate-500">MST: {company.tax_code||'—'} · {company.company_size||'—'}</p><p className="mt-1 text-xs text-slate-500">{company.email||'—'} · {company.phone||'—'}</p></div><Button onClick={()=>approve.mutate(company)} disabled={approve.isPending}>{approve.isPending?'Đang duyệt...':'Duyệt doanh nghiệp'}</Button></div>)}</div>:<Empty title="Không có yêu cầu chờ duyệt" description="Yêu cầu mới từ form doanh nghiệp sẽ hiện ở đây."/>}</Card>
    <Card className="p-6"><p className="eyebrow">Thanh toán</p><h2 className="section-title mt-2">Yêu cầu mua lượt</h2><p className="muted mt-2">Đơn đã tự cộng qua webhook sẽ không hiện ở đây. Với đơn cần kiểm tra thủ công, bạn có thể xác nhận cộng lượt hoặc từ chối.</p>{orders.isLoading?<Loading/>:orders.error?<ErrorState message={orders.error.message}/>:orders.data?.orders.length?<div className="mt-5 divide-y divide-slate-100">{orders.data.orders.map(order=><div className="flex flex-wrap items-center justify-between gap-4 py-4" key={order.id}><div><p className="font-extrabold">{order.company_name}</p><p className="mt-1 text-sm text-slate-600">{order.bucket==='cv'?'Chấm CV':'Lịch phỏng vấn'} · {order.units.toLocaleString('vi-VN')} lượt · {order.amount_vnd.toLocaleString('vi-VN')}đ</p><p className="mt-1 text-xs text-slate-400">{order.id} · {order.created_at}</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>approveOrder.mutate(order)} disabled={approveOrder.isPending||rejectOrder.isPending}>{approveOrder.isPending?'Đang cộng...':'Xác nhận & cộng lượt'}</Button><Button variant="danger" onClick={()=>{if(window.confirm(`Từ chối yêu cầu ${order.id}? Lượt sẽ không được cộng.`))rejectOrder.mutate(order);}} disabled={approveOrder.isPending||rejectOrder.isPending}>{rejectOrder.isPending?'Đang từ chối...':'Từ chối'}</Button></div></div>)}</div>:<Empty title="Không có yêu cầu mua lượt"/>}</Card>
    <Card className="p-6"><h2 className="section-title">Tài khoản doanh nghiệp và hạn mức</h2><p className="muted mt-1">Hạn mức dùng chung cho tất cả API key của một doanh nghiệp. Nhập 0 để khóa loại tác vụ đó; hệ thống không tự cấp quota.</p>{companies.isLoading?<Loading/>:companies.error?<ErrorState message={companies.error.message}/>:<div className="mt-5 divide-y divide-slate-100">{(companies.data?.companies||[]).filter(c=>c.is_active&&c.id!=='company_default').map(company=>{const active=editing?.id===company.id;return <div key={company.id} className="py-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-extrabold">{company.name}</p><p className="mt-1 text-xs text-slate-500">{company.slug} · {company.key_count||0} API key đang hoạt động</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>startQuota(company)}>Cấu hình hạn mức</Button><Button variant="secondary" onClick={()=>createKey.mutate(company)} disabled={createKey.isPending}>Cấp API key</Button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><QuotaCard label="CV được chấm" used={company.cv_used||0} limit={company.quota_cv||0}/><QuotaCard label="Lượt tạo lịch/phỏng vấn" used={company.interview_used||0} limit={company.quota_interview||0}/></div>{active&&<div className="mt-4 rounded-2xl border border-blue-200 bg-blue-50 p-4"><p className="font-extrabold text-slate-900">Cấu hình cho {company.name}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label><span className="label">Số CV được chấm</span><input className="field" type="number" min="0" max="1000000" value={cvLimit} onChange={e=>setCvLimit(e.target.value)}/></label><label><span className="label">Số lượt phỏng vấn</span><input className="field" type="number" min="0" max="1000000" value={interviewLimit} onChange={e=>setInterviewLimit(e.target.value)}/></label></div><p className="mt-3 text-xs text-slate-600">0 = chưa được phép dùng loại tác vụ này. Hạn mức hiện là tổng lượt đã cấp, không tự reset.</p><div className="mt-4 flex gap-2"><Button onClick={()=>saveQuota.mutate(company)} disabled={saveQuota.isPending}>{saveQuota.isPending?'Đang lưu...':'Lưu hạn mức'}</Button><Button variant="ghost" onClick={()=>setEditing(undefined)}>Hủy</Button></div></div>}</div>})}{!(companies.data?.companies||[]).some(c=>c.is_active&&c.id!=='company_default')&&<Empty title="Chưa có doanh nghiệp được duyệt"/>}</div>}</Card>
    {approval&&<Card className="border-emerald-200 bg-emerald-50 p-6"><p className="eyebrow">Tài khoản doanh nghiệp đã được duyệt</p><h2 className="section-title mt-2">{approval.company.name}</h2><p className="mt-2 text-sm font-semibold text-emerald-800">{approval.warning}</p>{approval.token&&<><code className="mt-5 block break-all rounded-2xl bg-slate-950 p-4 text-sm font-bold text-emerald-300">{approval.token}</code><Button className="mt-3" onClick={async()=>{await copy(approval.token||'');setNotice('Đã sao chép token khởi tạo.')}}>Sao chép token cho tài khoản cũ</Button></>}</Card>}{created&&<Card className="border-emerald-200 p-6"><p className="eyebrow">API key vừa cấp</p><h2 className="section-title mt-2">{created.company?.name||'Doanh nghiệp'}</h2><p className="mt-2 text-sm font-semibold text-amber-700">{created.warning}</p><code className="mt-5 block break-all rounded-2xl bg-slate-950 p-4 text-sm font-bold text-emerald-300">{created.api_key}</code><Button className="mt-3" onClick={async()=>{await copy(created.api_key);setNotice('Đã sao chép API key.')}}>Sao chép API key</Button>{notice&&<p className="mt-2 text-sm font-bold text-emerald-700">{notice}</p>}<pre className="mt-6 overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-100"><code>{`curl -sS -X POST "${origin}/api/v1/score-cv" \\
  -H "Authorization: Bearer ${key}" \\
  -F "cv_file=@./ung-vien.pdf" \\
  -F "jd_text=Mô tả công việc..."`}</code></pre></Card>}</div>;
}
function QuotaCard({label,limit,used}:{label:string;limit:number;used:number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-lg font-extrabold text-slate-950">{used.toLocaleString('vi-VN')} / {limit.toLocaleString('vi-VN')}</p><p className="text-xs text-slate-500">Còn lại: {Math.max(0,limit-used).toLocaleString('vi-VN')}</p></div>}
